=== dcwebmaven/EmpListwithUsernameElementXML/Employees6O2.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Employees">
     <xs:complexType>
     <xs:sequence>
              <xs:element name="Employee" minOccurs="0" maxOccurs="unbounded">
                   <xs:complexType>
                   <xs:sequence>
                      <xs:element minOccurs="1" maxOccurs="1" name="First" type="xs:token"/>
                      <xs:element minOccurs="1" maxOccurs="1" name="Last" type="xs:token"/>
					  <xs:element minOccurs="1" maxOccurs="1" name="UserName" type="UserType"/>
                      <xs:element minOccurs="0" maxOccurs="1" name="Phone" type="PhoneType"/>
                      <xs:element minOccurs="0" maxOccurs="1" name="Birthday" type="BirthdayType"/>
                      <xs:element minOccurs="0" maxOccurs="1" name="HourlyRate" type="RateType"/>
                    </xs:sequence>
                    </xs:complexType>
                    </xs:element>
     </xs:sequence>
	 </xs:complexType>  
             </xs:element>
			 
                     <xs:complexType name="PhoneType">
                     <xs:simpleContent>
                     <xs:extension base="xs:string">
                       <xs:attribute name="Type" type="LocationType" use="required"/>
                     </xs:extension>
                     </xs:simpleContent>
                    </xs:complexType>
					
	<xs:simpleType name="RateType">
	   <xs:restriction base="xs:decimal">
	      <xs:minInclusive value="20.00"/>
		  <xs:maxInclusive value="150.00"/>
	   </xs:restriction>
	</xs:simpleType>
					
	<xs:simpleType name="LocationType">
	   <xs:restriction base="xs:string">
	      <xs:enumeration value="Home"/>
		  <xs:enumeration value="Work"/>
		  <xs:enumeration value="Cell"/>
		  <xs:enumeration value="Fax"/>
	   </xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="BirthdayType">
	   <xs:restriction base="xs:date">
	      <xs:maxInclusive value="1995-01-01"/>
	   </xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="UserType">
	   <xs:restriction base="xs:token">
	     <xs:pattern value="([a-z]{5})"/>
	   </xs:restriction>
	</xs:simpleType>
   
</xs:schema>

=== dcwebmaven/EmpListwithUsernameElementXML/xmlLesson6Obj2.xml
<?xml version="1.0"?>
<!DOCTYPE Employees>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"xsi:noNamespaceSchemaLocation="Employees6O2.xsd">
<Employee>
<First>John</First>
<Last>Smith</Last>
<UserName>raven</UserName>
<Phone Type="Home">1-800-123-4567</Phone>
<Birthday>1960-05-25</Birthday>
<HourlyRate>35.85</HourlyRate>
</Employee>
<Employee>
<First>Amy</First>
<Last>Smith</Last>
<UserName>alive</UserName>
<Phone Type="Work">202-453-6868</Phone>
<Birthday>1968-08-17</Birthday>
<HourlyRate>50.00</HourlyRate>
</Employee>
</Employees>
